function [x_dot,k1,x_k1] = rk1_func(lamda,b1,x_prev,delta_t)
%RK1_FUNC
%    [X_DOT,K1,X_K1] = RK1_FUNC(LAMDA,B1,X_PREV,DELTA_T)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    07-Oct-2026 19:37:26

t2 = lamda.*x_prev;
x_dot = t2;
if nargout > 1
    k1 = t2;
end
if nargout > 2
    x_k1 = x_prev+b1.*delta_t.*t2;
end
end
