function [x_dot,k1,x_k1] = rk4_func(lamda,in2,x_prev,delta_t)
%RK4_FUNC
%    [X_DOT,K1,X_K1] = RK4_FUNC(LAMDA,IN2,X_PREV,DELTA_T)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    07-Oct-2026 19:40:32

a1 = in2(:,1);
a2 = in2(:,2);
a3 = in2(:,3);
b1 = in2(:,4);
b2 = in2(:,5);
b3 = in2(:,6);
b4 = in2(:,7);
t2 = lamda.*x_prev;
x_dot = t2;
if nargout > 1
    k1 = t2;
end
if nargout > 2
    t3 = a1.*delta_t.*t2;
    t4 = t3+x_prev;
    t5 = a2.*delta_t.*lamda.*t4;
    t6 = t5+x_prev;
    x_k1 = x_prev+delta_t.*(b1.*t2+b4.*lamda.*(x_prev+a3.*delta_t.*lamda.*t6)+b2.*lamda.*t4+b3.*lamda.*t6);
end
end
