function [x_dot,k1,x_k1] = rk2_func(lamda,a,b1,b2,x_prev,delta_t)
%RK2_FUNC
%    [X_DOT,K1,X_K1] = RK2_FUNC(LAMDA,A,B1,B2,X_PREV,DELTA_T)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    07-Oct-2026 09:45:37

t2 = lamda.*x_prev;
x_dot = t2;
if nargout > 1
    k1 = t2;
end
if nargout > 2
    x_k1 = x_prev+delta_t.*(b1.*t2+b2.*lamda.*(x_prev+a.*delta_t.*t2));
end
end
